# Generated by Django 2.2.3 on 2019-07-10 08:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30, null=True, verbose_name='doctor name')),
                ('Sex', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], max_length=10, null=True, verbose_name='sex')),
                ('Contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Contact')),
                ('Email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('Spec', models.CharField(blank=True, choices=[('physician', 'physician'), ('orthopedic', 'orthopedic'), ('cardiologist', 'cardiologist'), ('pediatrician', 'pediatrician')], max_length=10, null=True, verbose_name='specification')),
                ('av', models.BooleanField(default=True, verbose_name='Avaialable')),
                ('pa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Password')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='spec',
            field=models.CharField(blank=True, choices=[('physician', 'physician'), ('orthopedic', 'orthopedic'), ('cardiologist', 'cardiologist'), ('pediatrician', 'pediatrician')], max_length=10, null=True, verbose_name='specification'),
        ),
    ]
