# Generated by Django 2.2.3 on 2019-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190710_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='spec',
            field=models.CharField(blank=True, choices=[('physician', 'physician'), ('orthopedic', 'orthopedic'), ('cardiologist', 'cardiologist'), ('pediatrician', 'pediatrician')], max_length=15, null=True, verbose_name='specification'),
        ),
    ]
