# Generated by Django 2.2.3 on 2019-07-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190710_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Password'),
        ),
    ]
