# Generated by Django 2.2.3 on 2019-07-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_patient_pa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10, null=True, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10, null=True, verbose_name='sex'),
        ),
    ]
